# pyright: reportMissingImports=false
"""Re-exports for `app/grpc/gen/*_pb2*.py` (generated by `bun run generate-grpc`)."""

import ping_pb2
import ping_pb2_grpc

PingRequest = ping_pb2.PingRequest
PingResponse = ping_pb2.PingResponse
PingServiceStub = ping_pb2_grpc.PingServiceStub
PingServiceServicer = ping_pb2_grpc.PingServiceServicer
add_PingServiceServicer_to_server = ping_pb2_grpc.add_PingServiceServicer_to_server
